Repository CyBear-Jinni/cbj_app, pull requests merged in 2022-10, with the labels that each got.

#401 solves issue #398
  pubspec.yaml
Labels: hacktoberfest-accepted

#403 Fixed braking changes of some packages after last update
  lib/presentation/core/notifications.dart
Labels: hacktoberfest-accepted

#404 Update hi-IN.json
  assets/translations/hi-IN.json
Labels: hacktoberfest-accepted

#405 Created And reviewed en-IN.JSON
  assets/translations/en-IN.json
Labels: hacktoberfest-accepted

#408 correct some translation (id-ID)
  assets/translations/id-ID.json
Labels: hacktoberfest-accepted

#410 Created en-SG translation
  assets/translations/en-SG.json
Labels: hacktoberfest-accepted

#411 Created en-PK translation
  assets/translations/en-PK.json
Labels: hacktoberfest-accepted

#415 Update indonesian translation
  assets/translations/id-ID.json
Labels: hacktoberfest-accepted

#416 Created de-AT.json
  assets/translations/de-AT.json
Labels: hacktoberfest-accepted

#420 Added the bengali translation bn-IN.json.
  assets/translations/bn-IN.json
Labels: hacktoberfest-accepted

#421 Translation-correction
  assets/translations/hi-IN.json
Labels: hacktoberfest-accepted

#424 Created en-CA translation
  assets/translations/en-CA.json
Labels: hacktoberfest-accepted

#426 Created en-AU Translation
  assets/translations/en-AU.json
Labels: hacktoberfest-accepted

#425 add new translation file Malay (Malaysia)
  assets/translations/ms-MY.json
Labels: hacktoberfest-accepted

#427 Created en-BD Translation
  assets/translations/en-BD.json
Labels: hacktoberfest-accepted

#430 Replaced the phrases with more correct ones
  assets/translations/ru-RU.json
Labels: hacktoberfest-accepted

#437 Create am-ET.json
  assets/translations/am-ET.json
Labels: hacktoberfest-accepted

#438 Added Filipino language translation
  assets/translations/tl-PH.json
Labels: hacktoberfest-accepted

#443 Added ta-IN.json
  assets/translations/ta-IN.json
Labels: hacktoberfest-accepted

#436 Corrected Language errors hi-IN.json
  assets/translations/hi-IN.json
Labels: hacktoberfest-accepted

#441 fixed icons and sizes
  README.md
Labels: hacktoberfest-accepted

#446 Added en-PR.json
  assets/translations/en-PR.json
Labels: hacktoberfest-accepted

#447 Create zh-HK.json
  assets/translations/zh-HK.json
Labels: hacktoberfest-accepted

#450 Add tamil translation
  assets/translations/ta-IN.json
Labels: hacktoberfest-accepted

#454 Added demo mod with fake devices
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/application/more_connections_options/more_connections_options_bloc.dart
  lib/application/more_connections_options/more_connections_options_event.dart
  lib/application/more_connections_options/more_connections_options_state.dart
  lib/application/plus_button_settings/plus_button_settings_bloc.dart
  lib/application/plus_button_settings/plus_button_settings_event.dart
  lib/application/plus_button_settings/plus_button_settings_state.dart
  lib/domain/hub/i_hub_connection_repository.dart
  lib/infrastructure/hub_client/hub_client_demo.dart
  lib/infrastructure/hub_client/hub_connection_repository.dart
  lib/presentation/connect_to_hub/connect_to_hub_more_page.dart
  lib/presentation/connect_to_hub/connect_to_hub_page.dart
  lib/presentation/connect_to_hub/widgets/cbj_hub_in_network.dart
  lib/presentation/connect_to_hub_more/connect_to_hub_more_page.dart
  lib/presentation/connect_to_hub_more/widgets/connect_to_hub_more_widget.dart
  lib/presentation/plus_button/plus_button.dart
  lib/presentation/plus_button/widgets/plus_button_wighet.dart
  lib/presentation/routes/app_router.dart
Labels: hacktoberfest-accepted

#457 Added gu-IN
  assets/translations/gu-IN
Labels: hacktoberfest-accepted

#453 Added required translations in hi-IN.json
  assets/translations/hi-IN.json
Labels: hacktoberfest-accepted

#462 Added Japanese-Japan translation
  assets/translations/ja-JP.json
Labels: hacktoberfest-accepted

#464 🇳🇴 Bring Norwegian translations up to date
  assets/translations/nb-NO.json
Labels: hacktoberfest-accepted

#465 Update id-ID.json
  assets/translations/id-ID.json
Labels: hacktoberfest-accepted

#467 Added the pa-IN.json file
  assets/translations/pa-IN.json
Labels: hacktoberfest-accepted

#468 update Indonesian translation
  assets/translations/id-ID.json
Labels: hacktoberfest-accepted

#476 Added Malayalam Language ml-IN.json
  assets/translations/ml-IN.json
Labels: hacktoberfest-accepted

#478 Fix incorrect cbj_hub link in README.md
  README.md
Labels: hacktoberfest-accepted

#479 Create mr-IN.json
  assets/translations/mr-IN.json
Labels: hacktoberfest-accepted

#481 add pl-PL.json
  assets/translations/pl-PL.json
Labels: hacktoberfest-accepted

#477 Update ta-IN.json
  assets/translations/ta-IN.json
Labels: hacktoberfest-accepted

#488 enhancement: Added es-AR translation
  assets/translations/es-AR.json
Labels: hacktoberfest-accepted

#486 Translation in pa-IN.
  assets/translations/pa-IN.json
Labels: hacktoberfest-accepted

#489 Update ru-RU.json
  assets/translations/ru-RU.json
Labels: hacktoberfest-accepted

#497 Added Ukrainian translation
  assets/translations/uk-UA.json
Labels: hacktoberfest-accepted

#493 Software info text debugged
  lib/presentation/software_info/widgets/software_info_widget.dart
Labels: hacktoberfest-accepted

#491 Solved Pixel Overflow fixes #483
  lib/presentation/connect_to_hub/connect_to_hub_page.dart
Labels: hacktoberfest-accepted

#498 Verified and added en-FJ.json
  assets/translations/en-FJ.json
Labels: hacktoberfest-accepted

#494 Dependency Updated to the latest Version
  pubspec.yaml
Labels: hacktoberfest-accepted

#502 Add Vietnamese(vi-VN) translation
  assets/translations/vi-VN.json
Labels: hacktoberfest-accepted

#504 Create ne-NE.json
  assets/translations/ne-NE.json
Labels: hacktoberfest-accepted

#507 Add ko-KR.json
  assets/translations/ko-KR.json
Labels: hacktoberfest-accepted

#508 Added Youtube Tutorial to README
  README.md
Labels: hacktoberfest

#510 Issue-#428: Added en-JP.json
  assets/translations/en-JP.json
Labels: hacktoberfest-accepted

#511 Add Swedish Translation to App
  assets/translations/sv-SE.json
Labels: hacktoberfest-accepted

#512 Issue-#428: Added ur-PK.json
  assets/translations/ur-PK.json
Labels: hacktoberfest-accepted

#513 Adding translation for Hindi-PK
  assets/translations/hi-PK.json
Labels: hacktoberfest-accepted

#516 Added turkish (Turkiye) translation
  assets/translations/tr-TR.json
Labels: hacktoberfest-accepted

#514 Add Finnish translation
  assets/translations/fi-FI.json
Labels: hacktoberfest-accepted

#520 Issue #428: Updated hi-PK.json
  assets/translations/hi-PK.json
Labels: hacktoberfest-accepted

#519 Update Ne.json by correcting the blinds
  assets/translations/ne-NE.json
Labels: hacktoberfest-accepted

#521 Issue #428: Adding bn-BD.json
  assets/translations/bn-BD.json
Labels: hacktoberfest-accepted

#522 Complete fr-FR translations
  assets/translations/fr-FR.json
Labels: hacktoberfest-accepted

#523 updated open source image in readme.md
  README.md
Labels: hacktoberfest-accepted

#524 Update gj-IN.json
  assets/translations/gj-IN.json
Labels: hacktoberfest-accepted

#526 Hebrew translations
  assets/translations/he-IL.json
Labels: hacktoberfest-accepted

#528 Arabic-Palestine (West Bank and Gaza)
  assets/translations/ar-PS.json
Labels: hacktoberfest-accepted

#530 Create be-RU.json
  assets/translations/be-RU.json
Labels: hacktoberfest-accepted

#531 Create ka-IN.json
  assets/translations/ka-IN.json
Labels: hacktoberfest-accepted

#533 Update pt-BR.json
  assets/translations/pt-BR.json
Labels: hacktoberfest-accepted

#538 :bricks: ci: ignore `injection.config.dart` file
  .github/workflows/format.yml
Labels: hacktoberfest-accepted

#539 ADD: es-BO translation [CyBear-Jinni/cbj_app#428]
  assets/translations/es-BO.json
Labels: hacktoberfest-accepted

#542 Update ta-IN.json
  assets/translations/ta-IN.json
Labels: hacktoberfest-accepted

#545 be-in
  assets/translations/be-in.json
Labels: hacktoberfest-accepted

#537 Change deprecated methods to suggested solution
  ios/Podfile
  lib/infrastructure/core/shared_methods.dart
Labels: hacktoberfest-accepted

#549 Added zh-CN.json
  assets/translations/zh-CN.json
Labels: hacktoberfest-accepted

#552 Added nl-BE and nl-NL localization
  assets/translations/nl-BE.json
  assets/translations/nl-NL.json
Labels: hacktoberfest-accepted

#557 Update ml-IN
  assets/translations/ml-IN.json
Labels: hacktoberfest-accepted

#556 Updated ta-IN
  assets/translations/ta-IN.json
Labels: hacktoberfest-accepted

#555 Replaced json strings with DTOs
  lib/infrastructure/hub_client/hub_client_demo.dart
Labels: hacktoberfest-accepted

#560 created pt-PT.json file
  assets/translations/pt-PT.json
Labels: hacktoberfest-accepted

#562 feat: edited readme.md and added contributors list
  README.md
Labels: hacktoberfest-accepted

#566 Animation for summary container
  lib/infrastructure/hub_client/hub_client_demo.dart
  lib/presentation/home_page/tabs/smart_devices_tab/rooms_widgets/rom_widget.dart
Labels: hacktoberfest-accepted

#567 Corrected hi- IN and corrected format
  assets/translations/hi-IN.json
Labels: hacktoberfest-accepted

#568 Added new words to es- MX and fixed format
  assets/translations/es-MX.json
Labels: hacktoberfest-accepted

#570 Added af-Za translation
  assets/translations/af-ZA.json
Labels: hacktoberfest-accepted

#571 Added Pashto (Afghanistan) Translation
  assets/translations/ps-AF.json
Labels: hacktoberfest-accepted

#573 Added ar-AE translation
  assets/translations/ar-AE.json
Labels: hacktoberfest-accepted

#575 Added danish translations
  assets/translations/da-DK.json
Labels: hacktoberfest-accepted

#576 Added functionality to smart TV
  .idea/CBJ_App.iml
  lib/application/blinds/blinds_actor/blinds_actor_bloc.dart
  lib/application/smart_tv/smart_tv_actor/smart_tv_actor_bloc.dart
  lib/application/smart_tv/smart_tv_actor/smart_tv_actor_event.dart
  lib/domain/devices/device/i_device_repository.dart
  lib/infrastructure/core/gen/cbj_app_server/proto_gen_date.dart
  lib/infrastructure/core/gen/cbj_hub_server/proto_gen_date.dart
  lib/infrastructure/core/gen/cbj_hub_server/protoc_as_dart/cbj_hub_server.pbenum.dart
  lib/infrastructure/core/gen/cbj_hub_server/protoc_as_dart/cbj_hub_server.pbjson.dart
  lib/infrastructure/core/gen/security_bear/proto_gen_date.dart
  lib/infrastructure/devices/device/device_repository.dart
  lib/infrastructure/software_info/software_info_repository.dart
  lib/infrastructure/vendors/vendors_repository.dart
  lib/presentation/device_full_screen_page/printers/widgets/printer_widget.dart
  lib/presentation/device_full_screen_page/smart_tv/widgets/room_smart_tvs.dart
  lib/presentation/device_full_screen_page/smart_tv/widgets/smart_tv_widget.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: hacktoberfest-accepted

#577 Moving to Isar db [#536]
  .idea/CBJ_App.iml
  lib/domain/local_db/i_local_db_repository.dart
  lib/infrastructure/add_user_to_home/add_user_to_home_reposityory.dart
  lib/infrastructure/create_home/create_home_repository.dart
  lib/infrastructure/hive_local_db/hive_local_db.dart
  lib/infrastructure/hive_local_db/hive_objects/hub_entity_hive_model.dart
  lib/infrastructure/hive_local_db/hive_objects/remote_pipes_hive_model.dart
  lib/infrastructure/hive_local_db/hive_repository.dart
  lib/infrastructure/hive_local_db/home_hive.dart
  lib/infrastructure/hub_auth_facade/hub_auth_facade.dart
  lib/infrastructure/isar_local_db/isar_objects/home_entity_isar_model.dart
  lib/infrastructure/isar_local_db/isar_objects/hub_entity_isar_model.dart
  lib/infrastructure/isar_local_db/isar_objects/remote_pipes_isar_model.dart
  lib/infrastructure/isar_local_db/isar_repository.dart
  lib/infrastructure/user/user_repository.dart
  lib/presentation/device_full_screen_page/printers/widgets/room_printers.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: hacktoberfest-accepted

#582 Updated ur-PK.json
  assets/translations/ur-PK.json
Labels: hacktoberfest-accepted

#581 Upgraded Package versions to latest compatible versions Fixes #580
  linux/flutter/generated_plugins.cmake
  pubspec.yaml
  windows/flutter/generated_plugins.cmake
Labels: hacktoberfest-accepted

#591 Update ur-PK.json
  assets/translations/ur-PK.json
Labels: hacktoberfest-accepted

#593 Add pa-PK.json
  assets/translations/pa-PK.json
Labels: hacktoberfest, hacktoberfest-accepted

#592 Update pt-br.json
  assets/translations/pt-BR.json
Labels: hacktoberfest-accepted

#594 update pl-PL.jason
  assets/translations/pl-PL.json
Labels: hacktoberfest-accepted

#596 Updated es-MX
  assets/translations/es-MX.json
Labels: hacktoberfest-accepted

#595 Update fr-FR.json
  assets/translations/fr-FR.json
Labels: hacktoberfest-accepted

#600 catalan file post fork-reset
  assets/translations/ca-ES.json
Labels: hacktoberfest-accepted

#599 Added Divehi (Maldivian) translations.
  assets/translations/dv-MV.json
Labels: hacktoberfest-accepted

#602 Add files via upload
  assets/translations/ro-RO.json
Labels: hacktoberfest-accepted

#603 Add missing pt-BR translations
  assets/translations/pt-BR.json
Labels: hacktoberfest-accepted

#605 Add files via upload
  assets/translations/ar-SA.json
Labels: hacktoberfest, hacktoberfest-accepted

#604 Added Urdu-India translations
  assets/translations/ur-IN.json
Labels: hacktoberfest-accepted

#606 Add en-NZ.json
  assets/translations/en-NZ.json
Labels: hacktoberfest-accepted

#607 Added en-PH version
  assets/translations/en-ph.json
  assets/translations/en-za.json
Labels: hacktoberfest-accepted

#612 Added en-TT version
  en-TT.json
Labels: hacktoberfest-accepted

#613 Added en-BB version
  en-BB.json
Labels: hacktoberfest-accepted
